# Generated by Django 4.2.5 on 2023-10-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_social_website_profile_social_medium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
