# Generated by Django 4.2.5 on 2023-10-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', '-created']},
        ),
        migrations.AddField(
            model_name='message',
            name='message_read_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
